# Built with Jekyll 3.2.0

# Setup
title:               TDSTemplate.
tagline:             'a jekyll theme for minimal editions'
description:         'TDSTemplate is based on Ed, a Jekyll theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility.'
url:                 'http://sgolanka.github.io'
baseurl:             '/Template'

# About/contact
author:
  name:              Stan Golanka
  url:               wwww.trevor.org
  email:             sgolanka@trevor.org

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."


